export const CATEGORIES = [
    "Coding",
    "Physics",
    "Mathematics",
    "Chemistry",
    "Biology",
    "Sports",
    "Gaming",
    "Music",
    "Art",
    "Languages",
    "Cooking",
    "Finance",
    "Photography",
    "Writing",
    "Marketing",
    "Design",
    "Other"
  ];